### ISSUE TITLE
Container connector

### ISSUE THREAD

**Issue by ghost** [arcalot/arcaflow-engine#5]
Plugins need to be executed in containers. For this purpose, we need a connector that runs the plugins locally using the [Docker SDK](https://docs.docker.com/engine/api/sdk/). As an inspiration, the [ContainerSSH Docker test tooling](https://github.com/ContainerSSH/libcontainerssh/blob/main/internal/test/docker.go) may be used.

The connector must provide a `New()` function with a single struct as a configuration parameter set and return a struct pointer that provides the following interface:

```go
type DockerConnector interface {
    // Pull, create, and run container in a local Docker instance.
    Run(image string) (DockerContainer, error)
}

type DockerContainer interface {
    // Provide option to read from the standard output.
    io.Reader
    // Provide option to write to the standard input.
    io.Writer
    // Send a SIGTERM to the container, and then SIGKILL if it doesn't terminate.
    io.Closer
}
```

The module name for this should be `go.flow.arcalot.io/engine` and the package name should be `docker`.

**Comment by jaredoconnell** [comment]
Here is my code for the container connector: https://github.com/jaredoconnell/arcaflow-docker
