### ISSUE TITLE
Interrupt steps

### ISSUE THREAD

**Issue by janosdebugs** [arcalot/arcaflow-engine#9]
## Please describe what you would like to see in this project

In some cases, steps will need to be able to interrupt other steps.

## Please describe your use case

When a high priority issue is found, a workflow may follow down the high priority path and should cancel low priority tasks.

**Comment by dustinblack** [comment]
Superseded by https://github.com/arcalot/arcalot-round-table/blob/signals/art-decisions/proposals/2022-11-20-arcaflow-signals.md
